<a href="https://colab.research.google.com/github/davidogm/DataScience/blob/main/ITBD/notebooks/03numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy esencial**

Hay que tener en cuenta que NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

The fundamental package for scientific computing with Python

https://numpy.org/

La convención para importar NumPy siempre es esta:



In [ ]:
import numpy as np

In [ ]:
#Y de esta manera accedemos a la función norm, que calcula la norma (o módulo) de un array:

np.linalg.norm

# cuando lo ejecutamos vemos que ya está disponible


<function numpy.linalg.norm>

hay tantas funciones que además de usar el . podemos utilizar:

In [ ]:
np.lookfor("solve")

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.distutils.system_info.UmfpackNotFoundError
    UMFPACK sparse solver (https://www.cise.ufl.edu/research/sparse/umfpack/)
numpy.shares_memory
    Determine if two arrays share memory.
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
num

In [ ]:
?np
# ayuda en línea

In [ ]:
np.e

2.718281828459045

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.log(2)

0.6931471805599453

seguramente os preguntaréis que para qué tanta función matemática

hay que conocer este paquete siempre que se trabaja en python aunque no pensemos en lenguaje científico


Un array de NumPy es una colección de N elementos, como una secuencia de Python (por ejemplo, una lista). Para crear un array, la forma más directa es pasarle una secuencia a la función np.array.



In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

Es importante tener en cuenta que los arrays de NumPy son homogéneos, es decir, decir sus elementos son del mismo tipo. Podemos ver que si creamos un array con con objetos de tipos diferentes, se convertirán todos al tipo con más información. 
Para conocer al tipo del array, podemos usar el atributo dtype.



In [ ]:
a = np.array([1, 2, 3.0])
print(a.dtype)

float64


In [ ]:
# podemos forzar el tipo del array
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [ ]:
# convertir el array a a entero
a.astype(int)

array([1, 2, 3])

**Razones de eficiencia**

In [ ]:
N, M = 100, 100
a = np.empty(10000).reshape(N, M)
b = np.random.rand(10000).reshape(N, M)
c = np.random.rand(10000).reshape(N, M)

In [ ]:
%%timeit
for i in range(N):
    for j in range(M):
        a[i, j] = b[i, j] + c[i, j]


100 loops, best of 5: 6.88 ms per loop


In [ ]:
%%timeit
a = b + c

The slowest run took 86.18 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.02 µs per loop


¡1000 veces más rápido! Se hace fundamental vectorizar las operaciones y aprovechar al máximo la velocidad de NumPy.



Indexación de arrays

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[1,0]

4

In [ ]:
# secciones del array o subrangos
# empieza en 0 los índices y además es exclusivo, eso suele liar
# filas, columnas
a[:,::2]

# : es para abreviar, desde el principio hasta el final para
# indexar una matriz por columnas
# esta es una herramienta potente que al principio puede 
# parecer difícil de entender

array([[1, 3],
       [4, 6]])

In [ ]:
# equivalente pero sin omisión, el 2 indica los pares
a[0:3:2,0:3:]


array([[1, 2, 3]])


funciones para crear arrays



In [ ]:
import numpy as np

#utilizamos para inicializar
a = np.zeros(3)
# arrays of float, por defecto
a

array([0., 0., 0.])

In [ ]:
np.zeros((3,4))
# ojo, dos paréntesis si queremos dos dimensiones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#matriz identidad

np.identity(5)

#si la quiero de enteros
i=np.identity(5).astype(int)

i


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
i.shape

(5, 5)

In [ ]:
# creamos un array
z = np.linspace(1, 10, 5)

# lo visualizamos
print(z)

# vemos su tipo
#type(z[1])

# y accedemos a los elementos
z[2]

[ 1.    3.25  5.5   7.75 10.  ]


5.5

. salen las funciones
? sale información

In [ ]:
?z.shape

In [ ]:
np.random.seed(0)
# probar los argumentos poniendo ayudas y también viendo valores inclusivos y exclusivos
z1 = np.random.randint(3, 6, size=5)
z1


array([3, 4, 3, 4, 4])

In [ ]:
z1[0:4]

array([3, 4, 3, 4])

In [ ]:
z1[-1]

4